### ISSUE TITLE
Help Needed

### ISSUE THREAD

**Issue by scotie** [barakwei/IRelectra#11]
Hi Barak,

I was hoping you could help me out. It's a 2 part question:

1. I'm not too strong with c++ and I was struggling with the compilation.
I went back 3 commits on the master branch like you've suggested and it seem to have compiled ok.
But I'm not sure how to use it.

2. I generally need it not for Arduino - I'm using a IP to IR gateway and I need to send it the pronto hex format.

Could you point help me convert it? 

Thanks

**Comment by barakwei** [comment]
1. There's a sample usage in the README file. You can try and copy the code from there.
2. You'll have to give more information on your configuration, product, etc. I'm not familiar with pronto format, but you can definitely print raw format (basically led ON/OFF timing) and convert it online.

**Comment by scotie** [comment]
1. In this example an object is created with pin(D3) and I'm trying to run the code on my PC for now.
I would like to create several commands to test them before i try to port the code to my controller.

2. Pronto format looks something like this "0000 0080 005b 0000 0061 007e 003d 0020 001e...".
This is the gateway I'm using. https://www.kramerav.com/product/FC-26 
I need to send the commands vie TCP connection and the device will translate them to IR.

**Comment by barakwei** [comment]
I've created a program you can run and see the raw output - https://ideone.com/KO4NZl. You can change the parameters to the `send` method and get different results, look at the very last lines. You can copy the code and run it on your machine.

Regarding pronto, you're on your own, try to find a tool that converts from raw IR to pronto, or write one yourself. This link to the device you sent is interesting, but there are devices from Xiaomi (and other Chinese companies) which will probably make your life easier.

**Comment by scotie** [comment]
Thanks a lot for your help Barak!
