### ISSUE TITLE
Translated the library to Python

### ISSUE THREAD

**Issue by kebasaa** [barakwei/IRelectra#3]
Hi, I wanted to use this library with Python (on a Raspberry Pi), so I translated it. I attached it, can you upload it as an part of your github repository?
[IRelectra.py.txt](https://github.com/barakwei/IRelectra/files/242432/IRelectra.py.txt)

**Comment by barakwei** [comment]
First, thanks for your time and effort.
You can always send a pull request with your code, if you don't know how to do this there are plenty of guides online, and then it'll be as you uploaded it and not me. If you still prefer it that way, I can upload it myself.
The problem with the file is that it's missing some context - how to use it, and some demo code.

**Comment by bdsoha** [comment]
@kebasaa I tried using your code and I ran into a lot of problems. Did you ever actually test this?

**Comment by guysoft** [comment]
You could make python binding too

**Comment by bdsoha** [comment]
The library first needs to be properly tested. I am looking into porting this to `node` and using it with `homekit`.
