### ISSUE TITLE
Question (not an issue): Is the code tied to a specific type of remote?

### ISSUE THREAD

**Issue by ubialik** [barakwei/IRelectra#4]
Great work! thanks for sharing it :-)
The protocol for Electra's YKR-M/002E remote looks a bit different:
https://irforum.analysir.com/viewtopic.php?f=5&t=267

What type of remote are you using?

**Comment by guysoft** [comment]
I think thats the same remote I have.

**Comment by barakwei** [comment]
I'm using the black one (RC5 but it's the same as RC3). You're using the white one, which incidentally is what I have at work now, so support for that one should arrive soon.
![electra_rc_black](https://cloud.githubusercontent.com/assets/5232161/17130054/43060b4c-531f-11e6-9771-00e6103684f2.jpeg)
![electra_rc_white](https://cloud.githubusercontent.com/assets/5232161/17130058/4a06c08a-531f-11e6-841e-ee4396797afe.jpeg)

**Comment by barakwei** [comment]
I confirmed these are totally different remotes, I'll add this one hopefully soon

**Comment by ubialik** [comment]
Thank you!

**Comment by barakwei** [comment]
Please check `version-2.0` branch. The interface changed a bit, but it should support the new remote.

**Comment by barakwei** [comment]
Can I close this issue?
