### ISSUE TITLE
 Can not run the code with Arduino

### ISSUE THREAD

**Issue by AdiHen** [barakwei/IRelectra#5]
![error](https://cloud.githubusercontent.com/assets/21988878/18232762/9eea332c-72df-11e6-9db7-e3eb8991b942.JPG)

I can not run the code with Arduino
Can you help me please?
Thanks,
Adi

**Comment by barakwei** [comment]
1. First of all - the IRsend ctor in arduino doesn't accept a parameter, see [this](https://github.com/z3t0/Arduino-IRremote)
2. Which branch are you using? master or version-2.0?

**Comment by AdiHen** [comment]
1. I'm not sure what needs to change to make it work with Arduino.
    Can you write a simple example that will work with Arduino?
2.  I using version-2.0-tests
- By the way in the master version you should add { after void loop()

**Comment by barakwei** [comment]
1, Just don't give IRsend any parameters like [this](https://github.com/z3t0/Arduino-IRremote/blob/master/examples/IRsendRawDemo/IRsendRawDemo.ino)
2. I'm guessing you need to add `initializer_list` support to you arduino env. I have full c++ stl in my env, for some reason I assumed that arduino has it as well.

If you don't want to keep fighting these problems, you can just go back three commits in master and use the old implementation which is much simpler.

thanks for the tip about loop()!

**Comment by AdiHen** [comment]
Still unable to run it with the Arduino.
If you know about someone that succeed to run it with the Arduino please let me know.
Thanks.

**Comment by barakwei** [comment]
I'll probably do that myself at some point, use the watch button at the top to register for updates. I'll update the issue as well.

**Comment by barakwei** [comment]
Can you also write if you did anything else besides adding the .cpp and .h file to the Arduino IDE?

**Comment by AdiHen** [comment]
I tried to change some things. 
I do not have so much experience in programming, so maybe some of it really stupid.
anyway: 
#include "IRremote.h"   I changed to  #include <IRremote.h>
#include "IRelectra.h"   I changed to  #include <IRelectra.h>

i add the function:
  void setup()
{

}

void loop()
{
  IRsend irsend(D3);    I changed to  #include <IRelectra.h> 
IRsend irsend(D3);     I changed to   IRsend irsend;
  IRelectra e(&irsend);
  e.SendElectra(POWER_OFF, MODE_COOL, FAN_LOW, 24, SWING_ON, SLEEP_OFF);
}

that's pretty much it...

**Comment by barakwei** [comment]
If it's still relevant, see the changes needed in #6

**Comment by barakwei** [comment]
I got this to compile on Arduino, let me know if you still can't make it work.
