### ISSUE TITLE
C++ standard library usage

### ISSUE THREAD

**Issue by etinin** [barakwei/IRelectra#6]
What C++ standard library are you using?

I keep getting C++ vector errors. Manually modified my vector library to no avail.

Thanks

**Comment by barakwei** [comment]
I got this to compile (sorry, don't have a board to test right now) on arduino IDE with ArduinoSTL with changes to the IRelectra library and to Arduino STL.
Changes to IRelectra are in the [version-2.0-tests-arduino](https://github.com/barakwei/IRelectra/tree/version-2.0-tests-arduino).
Changes to ArduinoSTL are in [my fork](https://github.com/barakwei/ArduinoSTL). Changed `vector` and `map`.

**Comment by barakwei** [comment]
My changes to Arduino STL were merged few months ago, this should work now.
